import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddProperty1786807294116 implements MigrationInterface {
  name = 'AddProperty1786807294116';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "property_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "label" character varying NOT NULL, "addressLine1" character varying NOT NULL, "addressLine2" text, "city" character varying NOT NULL, "region" character varying NOT NULL, "postalCode" character varying NOT NULL, "accessNotes" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6bc642effd84808c1ee1e73bc1f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_8a192c020941b86d6f382ec819" ON "property_entity"  ("customerId") `,
    );
    // Hand-added (not generated by TypeORM's entity-diff, which never
    // infers a FK from `PropertyEntity.customerId`'s plain `@Column` —
    // there is no `@ManyToOne` relation decorator, intentionally, see
    // `property.entity.ts`). `ON DELETE RESTRICT` per spec §4.1: this
    // slice ships no delete operation for `Customer`, so a future slice
    // that adds one must decide its cascade behavior explicitly rather
    // than inheriting a permissive default set here. This migration is
    // the sole, authoritative source of this constraint — it must not
    // be regenerated from entity metadata later.
    await queryRunner.query(
      `ALTER TABLE "property_entity" ADD CONSTRAINT "fk_property_customer" FOREIGN KEY ("customerId") REFERENCES "customer_entity"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "property_entity" DROP CONSTRAINT "fk_property_customer"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_8a192c020941b86d6f382ec819"`,
    );
    await queryRunner.query(`DROP TABLE "property_entity"`);
  }
}
