import { MigrationInterface, QueryRunner } from 'typeorm';

export class MigrateBookingReferences1787355028101 implements MigrationInterface {
  name = 'MigrateBookingReferences1787355028101';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Existing booking rows are deterministic pre-Phase-1 seed data only
    // (spec §4.1 addendum). They are intentionally deleted here because the
    // legacy customerName/serviceType schema has no valid, deterministic
    // mapping to the new customerId/propertyId/serviceId reference model —
    // there is no upstream Customer/Property/Service to infer from a
    // free-text name/type string. This is an accepted destructive
    // legacy-data migration, not a production-preserving one: it must
    // never be copied as a pattern for a migration that runs against an
    // environment with real business data, and this migration itself must
    // not attempt to synthesize upstream Customer/Property/Service rows or
    // infer relationships from the deleted strings. Required, not merely
    // tidy: Postgres rejects ADD COLUMN ... NOT NULL (no DEFAULT) against a
    // table that already has rows, and this table is not guaranteed empty
    // at migration-run time (any dev DB that already ran `pnpm db:seed`
    // has 3 legacy rows).
    await queryRunner.query(`DELETE FROM "booking_entity"`);

    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "customerName"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "serviceType"`,
    );

    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD "customerId" uuid NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD "propertyId" uuid NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD "serviceId" uuid NOT NULL`,
    );
    await queryRunner.query(`ALTER TABLE "booking_entity" ADD "teamId" uuid`);
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD "pricingSnapshotPriceMinorUnits" integer NOT NULL`,
    );

    await queryRunner.query(
      `CREATE INDEX "IDX_0f5787a3583bdf1752250c24d7" ON "booking_entity" ("customerId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_07fbc2a657718477ed209609a1" ON "booking_entity" ("propertyId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_197a97348018a91264bef4d9dd" ON "booking_entity" ("serviceId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_7b275c50dec9745bbc5b076887" ON "booking_entity" ("teamId")`,
    );

    // Hand-added FKs — not generated by TypeORM's entity-diff, which never
    // infers a FK from a plain `@Column` with no `@ManyToOne` relation
    // decorator (booking.entity.ts). `ON DELETE RESTRICT` per spec §4.1,
    // matching every other hand-added FK's precedent in this codebase:
    // this slice ships no delete operation for Customer/Property/Service/
    // Team, so a future slice that adds one must decide its cascade
    // behavior explicitly rather than inheriting a default set here. This
    // migration is the sole, authoritative source of all four — they must
    // not be regenerated from entity metadata later.
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD CONSTRAINT "fk_booking_customer" FOREIGN KEY ("customerId") REFERENCES "customer_entity"("id") ON DELETE RESTRICT`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD CONSTRAINT "fk_booking_property" FOREIGN KEY ("propertyId") REFERENCES "property_entity"("id") ON DELETE RESTRICT`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD CONSTRAINT "fk_booking_service" FOREIGN KEY ("serviceId") REFERENCES "service_entity"("id") ON DELETE RESTRICT`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD CONSTRAINT "fk_booking_team" FOREIGN KEY ("teamId") REFERENCES "team_entity"("id") ON DELETE RESTRICT`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Down migration restores schema only; the legacy seed rows deleted by
    // up() are not restored — matching this migration's own up() rationale
    // and every other migration in this codebase, whose down()s reverse
    // schema, not data.
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP CONSTRAINT "fk_booking_team"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP CONSTRAINT "fk_booking_service"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP CONSTRAINT "fk_booking_property"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP CONSTRAINT "fk_booking_customer"`,
    );

    await queryRunner.query(
      `DROP INDEX "public"."IDX_7b275c50dec9745bbc5b076887"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_197a97348018a91264bef4d9dd"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_07fbc2a657718477ed209609a1"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_0f5787a3583bdf1752250c24d7"`,
    );

    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "pricingSnapshotPriceMinorUnits"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "teamId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "serviceId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "propertyId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" DROP COLUMN "customerId"`,
    );

    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD "serviceType" character varying NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "booking_entity" ADD "customerName" character varying NOT NULL`,
    );
  }
}
